<?php
/**
 * Simple Database Setup Script
 * Run this once to create the database and tables
 */

// Database configuration
$host = 'localhost';
$username = 'root';
$password = '';
$dbname = 'hcjcode_db';

echo "<h2>HCJ Code Editor - Database Setup</h2>";

try {
    // First, connect without specifying database to create it
    $pdo = new PDO("mysql:host=$host;charset=utf8mb4", $username, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
    
    // Create database if it doesn't exist
    $pdo->exec("CREATE DATABASE IF NOT EXISTS $dbname CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    echo "✓ Database '$dbname' created successfully.<br>";
    
    // Now connect to the specific database
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
    
    // Create users table
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            password VARCHAR(255) NOT NULL,
            email_verified BOOLEAN DEFAULT FALSE,
            reset_token VARCHAR(255) NULL,
            reset_token_expires DATETIME NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_email (email),
            INDEX idx_reset_token (reset_token)
        )
    ");
    echo "✓ Users table created successfully.<br>";
    
    // Create code_history table
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS code_history (
            id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            title VARCHAR(255) NOT NULL,
            html_code LONGTEXT,
            css_code LONGTEXT,
            js_code LONGTEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            INDEX idx_user_id (user_id),
            INDEX idx_created_at (created_at)
        )
    ");
    echo "✓ Code history table created successfully.<br>";
    
    echo "<br><strong style='color: green;'>✅ Database setup completed successfully!</strong><br>";
    echo "<br>You can now:<br>";
    echo "1. <a href='auth/signup.php'>Sign up for a new account</a><br>";
    echo "2. <a href='auth/login.php'>Login</a><br>";
    echo "3. <a href='index.php'>Go to Code Editor</a><br>";
    echo "<br><em>You can delete this setup.php file after successful setup.</em>";
    
} catch (PDOException $e) {
    echo "<strong style='color: red;'>❌ Database setup failed:</strong> " . $e->getMessage() . "<br>";
    echo "<br><strong>Troubleshooting:</strong><br>";
    echo "1. Make sure XAMPP/WAMP is running<br>";
    echo "2. Make sure MySQL service is started<br>";
    echo "3. Check if the database credentials are correct in config/database.php<br>";
    echo "4. Try refreshing this page<br>";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Setup - HCJ Code Editor</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h2 {
            color: #333;
            text-align: center;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Content is generated by PHP above -->
    </div>
</body>
</html>
